_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  actions_permissions: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  feeds: 0
  feeds_ex: 0
  feeds_log: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_google_cse: 0
  metatag_google_plus: 0
  metatag_views: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  search: 0
  shortcut: 0
  system: 0
  tamper: 0
  taxonomy: 0
  taxonomy_manager: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_options_limit: 0
  webform_spam_words: 0
  webform_ui: 0
  webform_views: 0
  webform_views_example: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  pathauto: 1
  webform_bootstrap: 1
  xmlsitemap: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap_barrio: 0
  songrequest_barrio: 0
  bootstrap_barrio_subtheme: 0
profile: standard
