_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: fec3e104-aee0-4304-8577-7d0ad453e806
name: "Arthur's Songbook"
mail: arthur@arthursongrequests.com
slogan: 'Request a song and I will sing it for you.'
page:
  403: ''
  404: ''
  front: /song-by-theme-or-genre
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
